name: blood_donation_app
description: A Flutter blood donation app with Firebase login & signup
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  device_preview: ^1.3.1
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.15.2

  # Firebase Authentication
  firebase_auth: ^5.7.0

  # UI Icons
  cupertino_icons: ^1.0.8

  # Optional: For maps & location later (if you add donor locator)
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  latlng: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  video_player: ^2.10.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1

  google_maps_flutter: ^2.9.0
  geocoding: ^2.2.0
  share_plus: ^12.0.0
  flutter_rating_bar: ^4.0.1
  
  

  fluttertoast: ^8.2.1
  

flutter:
  uses-material-design: true
